### ISSUE TITLE
项目无法兼容自定义注解，请求页面报错。

### ISSUE THREAD

**Issue by hfq-chenghongwei** [liuhuagui/smalldoc#1]

**Comment by liuhuagui** [comment]
具体代码和异常情况可以提供吗

**Comment by hfq-chenghongwei** [comment]
`javadoc: 错误 - 在 doclet 类com.github.liuhuagui.smalldoc.core.DefaultSmallDocletImpl中, 方法start已抛出异常错误java.lang.reflect.InvocationTargetException
java.lang.ClassCastException: java.lang.Boolean cannot be cast to [Lcom.sun.javadoc.AnnotationValue;
	at com.github.liuhuagui.smalldoc.core.storer.MappingDescStorer.analyseValue(MappingDescStorer.java:43)
	at com.github.liuhuagui.smalldoc.core.storer.MappingDescStorer.initValues(MappingDescStorer.java:27)
	at com.github.liuhuagui.smalldoc.core.storer.MappingDescStorer.<init>(MappingDescStorer.java:21)
	at com.github.liuhuagui.smalldoc.core.DefaultSmallDocletImpl.getMappingInfo(DefaultSmallDocletImpl.java:483)
	at com.github.liuhuagui.smalldoc.core.DefaultSmallDocletImpl.handleMethodDoc(DefaultSmallDocletImpl.java:114)
	at com.github.liuhuagui.smalldoc.core.DefaultSmallDocletImpl.getMehodDocsInfo(DefaultSmallDocletImpl.java:101)
	at com.github.liuhuagui.smalldoc.core.DefaultSmallDocletImpl.handleClassDoc(DefaultSmallDocletImpl.java:70)
	at com.github.liuhuagui.smalldoc.core.DefaultSmallDocletImpl.handleClassDocs(DefaultSmallDocletImpl.java:53)
	at com.github.liuhuagui.smalldoc.core.DefaultSmallDocletImpl.process(DefaultSmallDocletImpl.java:39)
	at com.github.liuhuagui.smalldoc.core.SmallDoclet.start(SmallDoclet.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
	at com.sun.tools.javadoc.Start.begin(Start.java:219)
	at com.sun.tools.javadoc.Start.begin(Start.java:205)
	at com.sun.tools.javadoc.Main.execute(Main.java:64)
	at com.github.liuhuagui.smalldoc.core.SmallDocContext.execute(SmallDocContext.java:86)
	at com.github.liuhuagui.smalldoc.web.SmallDocServlet.lambda$init$0(SmallDocServlet.java:39)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by liuhuagui** [comment]
希望给出解析的源码片段，将会尽快修复

**Comment by hfq-chenghongwei** [comment]
`String name = elementValuePair.element().name();
        Object value = elementValuePair.value().value();
        if (name.equals("name"))
            return new String[]{value.toString().trim()};//去除首尾空白字符
        AnnotationValue[] values = (AnnotationValue[]) value;
        String[] strings = new String[values.length];
        int i = 0;
        for (AnnotationValue v : values) {
            String s = v.value().toString().trim();//去除首尾空白字符
            if (name.equals("method")) {
                strings[i++] = s.substring(s.lastIndexOf(".") + 1, s.length());
            } else {
                strings[i++] = s;
            }
        }
        return strings;`
    if (name.equals("name"))
            return new String[]{value.toString().trim()};//去除首尾空白字符
        AnnotationValue[] values = (AnnotationValue[]) value;
以 name 判断，会继续执行，但注解返回的不是数据，是对象。抛出强转失败，应该判断Object value 是不是数组，再决定执行

**Comment by liuhuagui** [comment]
如果方便，可以提pr

**Comment by liuhuagui** [comment]
多谢了

**Comment by liuhuagui** [comment]
方便给出您的自定义注解源码片段吗

**Comment by liuhuagui** [comment]
[2.3.1更新日志](https://github.com/liuhuagui/smalldoc/blob/master/doc/smalldoc-2.3.1.md)
